// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import "strconv"

type MetricType int8

const (
	MetricTypeGauge        MetricType = 0
	MetricTypeTimer        MetricType = 1
	MetricTypeHistogram    MetricType = 2
	MetricTypeSet          MetricType = 3
	MetricTypeDistribution MetricType = 4
	MetricTypeCount        MetricType = 5
)

var EnumNamesMetricType = map[MetricType]string{
	MetricTypeGauge:        "Gauge",
	MetricTypeTimer:        "Timer",
	MetricTypeHistogram:    "Histogram",
	MetricTypeSet:          "Set",
	MetricTypeDistribution: "Distribution",
	MetricTypeCount:        "Count",
}

var EnumValuesMetricType = map[string]MetricType{
	"Gauge":        MetricTypeGauge,
	"Timer":        MetricTypeTimer,
	"Histogram":    MetricTypeHistogram,
	"Set":          MetricTypeSet,
	"Distribution": MetricTypeDistribution,
	"Count":        MetricTypeCount,
}

func (v MetricType) String() string {
	if s, ok := EnumNamesMetricType[v]; ok {
		return s
	}
	return "MetricType(" + strconv.FormatInt(int64(v), 10) + ")"
}
